### PR TITLE
fix the data structure for params data

### PR DESCRIPTION
**Pull request by hendjecson**

### CODE REVIEW

**Comment by hendjecson** [comment]
why Set and not List?

**Comment by ofrnsb** [comment]
> why Set and not List?

As far as I can understand, the upcoming data will be unique to each other

**Comment by hendjecson** [comment]
> > why Set and not List?
> 
> As far as I can understand, the upcoming data will be unique to each other

but would it be the same if we set the DTO as unique?

**Comment by ofrnsb** [comment]
> > > why Set and not List?
> > 
> > 
> > As far as I can understand, the upcoming data will be unique to each other
> 
> but would it be the same if we set the DTO as unique?

We could, but its up to you tho

**Pull request closed without merging**
